# Generated by Django 5.1.1 on 2024-10-13 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biryani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('biryani', 'Biryani'), ('veg_starters', 'Veg Starters'), ('nonveg_starters', 'Non-Veg Starters'), ('veg_curries', 'Veg Curries'), ('nonveg_curries', 'Non-Veg Curries'), ('fried_rice', 'Fried Rice'), ('tandoori', 'Tandoori')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('biryani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop4.biryani')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
