# Generated by Django 5.1.1 on 2024-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop4', '0007_rename_placed_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
