# Generated by Django 5.1.1 on 2024-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop4', '0011_rename_order_date_order_created_at_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
