# Generated by Django 5.1.1 on 2024-10-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop4', '0013_remove_orderitem_order_remove_orderitem_biryani_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
